{"name": "Неуспешный вход с неверным паролем", "status": "passed", "description": "Проверка ошибки при входе с неверным паролем", "steps": [{"name": "Авторизация пользователя: POST /api/auth/login", "status": "passed", "parameters": [{"name": "email", "value": "'emoreno@example.com'"}, {"name": "password", "value": "''"}], "start": 1719860653518, "stop": 1719860654179}], "parameters": [{"name": "password", "value": "''"}], "start": 1719860653517, "stop": 1719860654181, "uuid": "6004971c-6dc9-4e18-ae71-e17439944e0a", "historyId": "0a64d4b6d1797ae683c0784dc1b12e04", "testCaseId": "0a64d4b6d1797ae683c0784dc1b12e04", "fullName": "tests.test_user.TestLoginUser#test_login_bad_password_failure", "labels": [{"name": "feature", "value": "Вход пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "NB-4179"}, {"name": "thread", "value": "11668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}